### ISSUE TITLE
alias_generator causes stack level too deep error with jekyll-2.1.0

### ISSUE THREAD

**Issue by ghost** [tsmango/jekyll_alias_generator#12]
I'm getting `~/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/jekyll-2.1.0/lib/jekyll/cleaner.rb:59: stack level too deep (SystemStackError)` while generating a Jekyll page and was able to reproduce the error with a minimal setup (joelmeyerhamme/jekyll_alias_issue#1):

``` bash
jekyll new jekyll_alias_issue && cd jekyll_alias_issue
mkdir _plugins
curl https://raw.githubusercontent.com/tsmango/jekyll_alias_generator/master/_plugins/alias_generator.rb\
  > _plugins/alias_generator.rb
rm *.html *.md
cat <<EOF > index.md

---
layout: page
title: Index
alias: "/index/"

---

This is the base Jekyll theme.
EOF
jekyll build
```

**Comment by alessandrococco** [comment]
Same problem, thank you @joelmeyerhamme for the fix! :+1:

**Comment by SummerBuger** [comment]
oh, my English is poor, and I know a little about ruby, who can tell me how to fix this problem step by step, thx!!!
