### ISSUE TITLE
Stack level too deep error

### ISSUE THREAD

**Issue by fareez-ahamed** [tsmango/jekyll_alias_generator#14]
It was working fine on jekyll 1.4.3... Now I updated ruby to 2.0 and jekyll to 2.1.1 and getting the following error

```
Configuration file: /home/fareez/sites/fareez.info/_config.yml
            Source: /home/fareez/sites/fareez.info
       Destination: /home/fareez/sites/fareez.info/_site
      Generating... 
/home/fareez/.rvm/gems/ruby-2.0.0-p481/bin/ruby_executable_hooks:15: stack level too deep (SystemStackError)
```

**Comment by yuletide** [comment]
Still getting this error with ruby 2.1 and jekyll 2.5.3

**Comment by tsmango** [comment]
Sorry for the delay, everyone. This has been resolved in master. Thanks for all of the pull requests!
