### ISSUE TITLE
there is no gem distribution jekyll-alias-generator

### ISSUE THREAD

**Issue by ssbarnea** [tsmango/jekyll_alias_generator#23]

**Comment by tsmango** [comment]
You just need to put `alias_generator.rb` in your plugins directory inside of your jekyll project.

**Comment by ssbarnea** [comment]
Putting a source code file inside is clearly not the best way to distribute code as this would involve watching the repository for changes and manually updating the file on a new release.

Have a look at other Jekyll modules that are distributed using gem packages:

```
gem 'jekyll-redirect-from'
gem 'jekyll-sitemap'
gem 'jekyll-minifier'
```

**Comment by tsmango** [comment]
Right, sorry, I know you can distribute them as gems, I'm really not sure if I'd bother doing it for this plugin, though. It's not going to get any new features and if it stops working in a future release of jekyll, it'll be easy enough to check back for a fix. Sorry about that. 

But `jekyll-redirect-from` is already a gem and looks like it does basically what my plugin does anyway.
